-- Preserve the legacy songs.artist display value while making every credited
-- artist independently browseable and searchable.
CREATE TABLE song_artists (
    id           BIGSERIAL PRIMARY KEY,
    song_id      BIGINT NOT NULL REFERENCES songs(id) ON DELETE CASCADE,
    artist_name  TEXT NOT NULL,
    artist_key   TEXT NOT NULL,
    artist_py    TEXT NOT NULL DEFAULT '',
    artist_init  TEXT NOT NULL DEFAULT '',
    artist_order INT NOT NULL DEFAULT 0,
    CONSTRAINT uk_song_artists_song_key UNIQUE (song_id, artist_key)
);

CREATE INDEX idx_song_artists_song_order ON song_artists (song_id, artist_order);
CREATE INDEX idx_song_artists_key ON song_artists (artist_key);
CREATE INDEX idx_song_artists_name_trgm ON song_artists USING gin (artist_name gin_trgm_ops);
CREATE INDEX idx_song_artists_py ON song_artists (artist_init, artist_py);

-- Existing rows are copied without changing songs.artist or any source file.
-- Pinyin for newly synchronized rows is generated by ArtistCreditService;
-- legacy rows retain empty relation pinyin and safely fall back to songs.* in
-- the search query until a later write path refreshes them.
INSERT INTO song_artists (song_id, artist_name, artist_key, artist_order)
SELECT s.id,
       trim(parts.artist_name),
       lower(regexp_replace(trim(parts.artist_name), '[[:space:]]+', '', 'g')),
       (parts.artist_order - 1)::INT
FROM songs s
CROSS JOIN LATERAL regexp_split_to_table(COALESCE(s.artist, ''), '[_、&＆+]+')
    WITH ORDINALITY AS parts(artist_name, artist_order)
WHERE trim(parts.artist_name) <> ''
ON CONFLICT (song_id, artist_key) DO NOTHING;
